# Generated by Django 4.2 on 2023-06-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='poppypetals/static/onlinestore/images/product'),
        ),
    ]
