# Generated by Django 4.2 on 2023-06-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tshirt'), ('S', 'Skirt'), ('P', 'Pant'), ('J', 'Jacket'), ('SO', 'Socks')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='images/product/'),
        ),
    ]
