# Generated by Django 4.2 on 2023-06-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0004_alter_item_category_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tshirt'), ('S', 'Skirt'), ('P', 'Pant'), ('J', 'Jacket'), ('SO', 'Socks'), ('HB', 'Headband')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True),
        ),
    ]
