# Generated by Django 4.2 on 2023-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tshirt'), ('SH', 'Shirt'), ('SK', 'Skirt'), ('P', 'Pant'), ('J', 'Jacket'), ('SO', 'Socks'), ('HB', 'Headband'), ('CO', 'Combination')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2, null=True),
        ),
    ]
