# Generated by Django 4.2 on 2023-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0006_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'Baby'), ('T', 'Toddler'), ('K', 'Kid'), ('A', 'All')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T', 'Tshirt'), ('SH', 'Shirt'), ('SK', 'Skirt'), ('P', 'Pant'), ('J', 'Jacket'), ('SO', 'Socks'), ('HB', 'Headband'), ('CO', 'Combination'), ('DU', 'Dungaree')], max_length=2, null=True),
        ),
    ]
