# Generated by Django 4.2 on 2023-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0009_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('B', 'Boys'), ('G', 'Girls'), ('BT', 'Both')], max_length=8, null=True),
        ),
    ]
