# Generated by Django 4.2 on 2023-06-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0011_cart_alter_item_category_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('B', 'Baby'), ('T', 'Toddler'), ('K', 'Kid'), ('AL', 'All'), ('TK', 'Toddler and Kid'), ('BK', 'Baby and Toddler')], max_length=8, null=True),
        ),
    ]
